"""Add file_summaries table

Revision ID: 7d88c707ff7d
Revises: e1af585f48f7
Create Date: 2026-09-05 14:10:51.199969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d88c707ff7d'
down_revision: Union[str, Sequence[str], None] = 'e1af585f48f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_file_id', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repo_file_id'], ['repo_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_summaries_content_hash'), 'file_summaries', ['content_hash'], unique=False)
    op.create_index(op.f('ix_file_summaries_id'), 'file_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_summaries_id'), table_name='file_summaries')
    op.drop_index(op.f('ix_file_summaries_content_hash'), table_name='file_summaries')
    op.drop_table('file_summaries')
    # ### end Alembic commands ###
