"""Add code_chunks table

Revision ID: f8366198b9e2
Revises: 0afd19f5833a
Create Date: 2026-09-12 14:30:23.715995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f8366198b9e2'
down_revision: Union[str, Sequence[str], None] = '0afd19f5833a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_file_id', sa.Integer(), nullable=False),
    sa.Column('code_content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['repo_file_id'], ['repo_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_id'), 'code_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
